Add getTags #24
chicking/spring-realworld-example pull request #25
Opened 2019-03-11 15:41 UTC by clil

2019-03-11 15:43 UTC, y0ngjae commented on src/test/java/study/godofchicken/realworldexample/controllers/TagControllerAPITest.java
> +@RunWith(SpringRunner.class)
스프링이 뭔지 한개도 모르겠습니다

2019-03-11 15:43 UTC, y0ngjae commented on src/main/java/study/godofchicken/realworldexample/controllers/TagController.java
> +    /**
인덴트가 이상합니다

2019-03-12 05:14 UTC, dhlim-dev requested changes
1. TagService 만들기
2. TagController Unit Test 만들기

2019-03-12 05:14 UTC, gongzza commented on src/main/java/study/godofchicken/realworldexample/controllers/TagController.java
> +        tagList.add("angularjs");
tagList를 TagService를 만들어서 TagService에서 가져오도록 수정해 주세요.

2019-03-12 05:14 UTC, gongzza commented on src/test/java/study/godofchicken/realworldexample/controllers/TagControllerAPITest.java
> +public class TagControllerAPITest extends SpringBootApiTest {
클래스명을 다른 클래스명과 동일하게 맞춰주세요.

2019-03-15 15:05 UTC, clil reviewed
태그 서비스  확인

2019-03-15 15:07 UTC, dhlim-dev approved these changes

2019-03-15 15:07 UTC, merged

2019-03-15 15:07 UTC, gongzza commented
fixed #24